{
 "title": "Speech music discrimination",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(sm_music_probability, job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(sm_music_probability, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Järviradio soittaa",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sm_music_probability{instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Music probability",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sm_music_probability{instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Retries",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sm_stream_retries_total{instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Virtual memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"$instance\", job=\"$job\"}"
    }
   ]
  }
 ]
}